import type { ErrorCode } from './error-code'

export const ERROR_MESSAGE: Record<ErrorCode, string> = {
    VALIDATION_ERROR: '요청 데이터가 유효하지 않습니다',
    NOT_FOUND: '요청한 리소스를 찾을 수 없습니다',
    UNAUTHORIZED: '인증이 필요합니다',
    FORBIDDEN: '접근 권한이 없습니다',
    RATE_LIMIT_EXCEEDED: '요청 한도를 초과했습니다',
    INTERNAL_ERROR: '서버 내부 오류가 발생했습니다',
    EXTERNAL_API_ERROR: '외부 API 호출에 실패했습니다',

    STORAGE_UPLOAD_FAILED: '파일 업로드에 실패했습니다',
    STORAGE_DELETE_FAILED: '파일 삭제에 실패했습니다',
    IMAGE_PROCESS_FAILED: '이미지 처리에 실패했습니다',
    IMAGE_GENERATE_FAILED: '이미지 생성에 실패했습니다',
    FONT_NOT_FOUND: '요청한 폰트를 찾을 수 없습니다',
    ICON_LOAD_FAILED: '아이콘 로드에 실패했습니다',
    NOTIFICATION_SEND_FAILED: '알림 전송에 실패했습니다',
    AI_SUMMARIZE_FAILED: 'AI 요약 생성에 실패했습니다',
    API_TOKEN_INVALID: 'API 토큰이 유효하지 않습니다',
    SERVICE_NOT_CONFIGURED: '서비스가 구성되지 않았습니다',

    BADGE_INVALID_DIMENSIONS: '뱃지 크기가 유효하지 않습니다',
    BADGE_INVALID_COLOR: '뱃지 색상이 유효하지 않습니다',

    BLOG_POST_NOT_FOUND: '게시글을 찾을 수 없습니다',
    BLOG_COMMENT_NOT_FOUND: '댓글을 찾을 수 없습니다',
    BLOG_CATEGORY_NOT_FOUND: '카테고리를 찾을 수 없습니다',
    BLOG_NOT_COMMENT_OWNER: '댓글 작성자만 수정/삭제할 수 있습니다',
    BLOG_IMAGE_TOO_LARGE: '이미지 크기가 제한을 초과했습니다',
    BLOG_IMAGE_INVALID_TYPE: '허용되지 않는 이미지 형식입니다',

    WEATHER_KMA_API_ERROR: '기상청 API 호출에 실패했습니다',
    WEATHER_INVALID_GRID: '유효하지 않은 격자 좌표입니다',
    WEATHER_DATA_NOT_FOUND: '기상 데이터를 찾을 수 없습니다',
    WEATHER_KEY_INVALID: '날씨 API 키가 유효하지 않습니다',
    WEATHER_KEY_RATE_LIMIT: '날씨 API 일일 요청 한도를 초과했습니다',

    HN_STORY_NOT_FOUND: 'HN 스토리를 찾을 수 없습니다',
    HN_FETCH_FAILED: 'HN 데이터 수집에 실패했습니다',
    HN_CRON_SECRET_INVALID: 'Cron 시크릿이 유효하지 않습니다',
    HN_WEBHOOK_REGISTER_FAILED: '웹훅 등록에 실패했습니다',

    MAIL_ACCOUNT_NOT_FOUND: '메일 계정을 찾을 수 없습니다',
    MAIL_ACCOUNT_LIMIT_EXCEEDED: '메일 계정 등록 한도를 초과했습니다',
    MAIL_FOLDER_NOT_FOUND: '메일 폴더를 찾을 수 없습니다',
    MAIL_MESSAGE_NOT_FOUND: '메일 메시지를 찾을 수 없습니다',
    MAIL_ATTACHMENT_NOT_FOUND: '첨부 파일을 찾을 수 없습니다',
    MAIL_PROVIDER_ERROR: '메일 서버 연결에 실패했습니다',
    MAIL_CONNECTION_FAILED: '메일 서버에 연결할 수 없습니다',
    MAIL_SYNC_IN_PROGRESS: '이미 동기화가 진행 중입니다',
    MAIL_CREDENTIALS_INVALID: '메일 계정 인증 정보가 유효하지 않습니다',
    MAIL_SEND_FAILED: '메일 발송에 실패했습니다',
    MAIL_UPLOAD_TOO_LARGE: '파일 크기가 제한을 초과했습니다',
    MAIL_UPLOAD_INVALID_TYPE: '허용되지 않는 파일 형식입니다',
    MAIL_UPLOAD_NOT_FOUND: '업로드된 파일을 찾을 수 없습니다',
    MAIL_UPLOAD_BLOCKED_EXTENSION: '보안상 허용되지 않는 파일 확장자입니다',
    MAIL_BLOCKED_HOST: '내부 네트워크 주소는 사용할 수 없습니다',
    MAIL_OAUTH_ACCOUNT_MISMATCH: 'OAuth 계정 소유권이 일치하지 않습니다',
    MAIL_OAUTH_STATE_INVALID: 'OAuth state가 유효하지 않습니다',
    MAIL_OAUTH_EXCHANGE_FAILED: 'OAuth 토큰 교환에 실패했습니다',
    MAIL_ACCOUNT_ALREADY_EXISTS: '이미 연결된 메일 계정입니다',

    SPOTIFY_ACCOUNT_NOT_FOUND: 'Spotify 계정을 찾을 수 없습니다',
    SPOTIFY_ACCOUNT_ALREADY_EXISTS: '이미 연결된 Spotify 계정입니다',
    SPOTIFY_OAUTH_STATE_INVALID: 'Spotify OAuth state가 유효하지 않습니다',
    SPOTIFY_OAUTH_EXCHANGE_FAILED: 'Spotify OAuth 토큰 교환에 실패했습니다',
    SPOTIFY_API_ERROR: 'Spotify API 호출에 실패했습니다',
    SPOTIFY_KEY_INVALID: 'Spotify API 키가 유효하지 않습니다',
    SPOTIFY_WIDGET_TOKEN_NOT_FOUND: 'Spotify 위젯 토큰을 찾을 수 없습니다',
    SPOTIFY_WIDGET_TOKEN_INACTIVE: 'Spotify 위젯 토큰이 비활성화되었습니다',

    RESUME_NOT_FOUND: '이력서를 찾을 수 없습니다',
    RESUME_NOT_OWNER: '이력서 소유자만 수정/삭제할 수 있습니다',
}
