import type { ErrorCode } from './error-code'
import { ERROR_MESSAGE } from './error-message'

export type AppError = {
    code: ErrorCode
    message: string
    statusCode: number
    details?: Record<string, unknown>
}

const STATUS_MAP: Record<string, number> = {
    VALIDATION_ERROR: 400,
    NOT_FOUND: 404,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    RATE_LIMIT_EXCEEDED: 429,
    INTERNAL_ERROR: 500,
    EXTERNAL_API_ERROR: 502,

    STORAGE_UPLOAD_FAILED: 500,
    STORAGE_DELETE_FAILED: 500,
    STORAGE_PRESIGN_FAILED: 500,
    IMAGE_PROCESS_FAILED: 422,
    IMAGE_GENERATE_FAILED: 500,
    FONT_NOT_FOUND: 404,
    ICON_LOAD_FAILED: 422,
    NOTIFICATION_SEND_FAILED: 502,
    AI_SUMMARIZE_FAILED: 502,
    API_TOKEN_INVALID: 401,
    SERVICE_NOT_CONFIGURED: 503,

    BADGE_INVALID_DIMENSIONS: 400,
    BADGE_INVALID_COLOR: 400,

    BLOG_POST_NOT_FOUND: 404,
    BLOG_COMMENT_NOT_FOUND: 404,
    BLOG_CATEGORY_NOT_FOUND: 404,
    BLOG_IMAGE_TOO_LARGE: 413,
    BLOG_IMAGE_INVALID_TYPE: 422,

    WEATHER_KMA_API_ERROR: 502,
    WEATHER_INVALID_GRID: 400,
    WEATHER_DATA_NOT_FOUND: 404,
    WEATHER_KEY_INVALID: 401,
    WEATHER_KEY_RATE_LIMIT: 429,

    MAIL_ACCOUNT_NOT_FOUND: 404,
    MAIL_ACCOUNT_LIMIT_EXCEEDED: 400,
    MAIL_FOLDER_NOT_FOUND: 404,
    MAIL_MESSAGE_NOT_FOUND: 404,
    MAIL_ATTACHMENT_NOT_FOUND: 404,
    MAIL_ATTACHMENT_DOWNLOAD_FAILED: 502,
    MAIL_PROVIDER_ERROR: 502,
    MAIL_CONNECTION_FAILED: 502,
    MAIL_SYNC_IN_PROGRESS: 409,
    MAIL_CREDENTIALS_INVALID: 401,
    MAIL_SEND_FAILED: 502,
    MAIL_UPLOAD_TOO_LARGE: 413,
    MAIL_UPLOAD_INVALID_TYPE: 422,
    MAIL_UPLOAD_NOT_FOUND: 404,
    MAIL_OAUTH_STATE_INVALID: 400,
    MAIL_OAUTH_EXCHANGE_FAILED: 502,
    MAIL_ACCOUNT_ALREADY_EXISTS: 409,

    SPOTIFY_ACCOUNT_NOT_FOUND: 404,
    SPOTIFY_ACCOUNT_ALREADY_EXISTS: 409,
    SPOTIFY_OAUTH_STATE_INVALID: 400,
    SPOTIFY_OAUTH_EXCHANGE_FAILED: 502,
    SPOTIFY_API_ERROR: 502,
    SPOTIFY_KEY_INVALID: 401,
    SPOTIFY_WIDGET_TOKEN_NOT_FOUND: 404,
    SPOTIFY_WIDGET_TOKEN_INACTIVE: 403,

    RESUME_NOT_FOUND: 404,

    CALENDAR_EVENT_NOT_FOUND: 404,
    CALENDAR_SUBSCRIPTION_NOT_FOUND: 404,
    CALENDAR_CALDAV_AUTH_FAILED: 401,
    CALENDAR_ICS_PARSE_FAILED: 422,
    CALENDAR_ICS_TOO_LARGE: 413,
    CALENDAR_GROUP_NOT_FOUND: 404,
    CALENDAR_GROUP_HAS_EVENTS: 409,
    CALENDAR_INVALID_DATE_RANGE: 400,

    DRIVE_ASSET_NOT_FOUND: 404,
    DRIVE_FILE_TOO_LARGE: 413,
    DRIVE_INVALID_MIME_TYPE: 422,
    DRIVE_DUPLICATE_FILE: 409,
    DRIVE_QUOTA_EXCEEDED: 413,
    DRIVE_FOLDER_NOT_FOUND: 404,
    DRIVE_FOLDER_CIRCULAR_REF: 400,
    DRIVE_FOLDER_NAME_DUPLICATE: 409,
    DRIVE_L2_UPLOAD_FAILED: 500,
    DRIVE_L2_DOWNLOAD_FAILED: 502,
    DRIVE_L3_UPLOAD_FAILED: 500,
    DRIVE_L3_DOWNLOAD_FAILED: 502,
    DRIVE_ALL_TIERS_FAILED: 500,
    DRIVE_UPLOAD_EVENT_FAILED: 500,

    LOG_EVENT_NOT_FOUND: 404,
    LOG_BATCH_TOO_LARGE: 413,
    LOG_INGEST_FAILED: 500,
    LOG_DEVICE_KEY_INVALID: 401,
    LOG_DEVICE_KEY_RATE_LIMIT: 429,

    METRICS_TOKEN_INVALID: 401,
    METRICS_TOKEN_FORBIDDEN: 403,
    METRICS_TOKEN_NOT_FOUND: 404,
    METRICS_TOKEN_RATE_LIMIT: 429,
    METRICS_PAYLOAD_TOO_LARGE: 413,
    METRICS_BATCH_TOO_LARGE: 413,
    METRICS_DEVICE_NOT_FOUND: 404,
    METRICS_INGEST_FAILED: 500,

    AI_PROVIDER_NOT_FOUND: 404,
    AI_PROVIDER_ALREADY_EXISTS: 409,
    AI_CREDENTIALS_INVALID: 401,
    AI_REAUTH_REQUIRED: 401,
    AI_TOKEN_REFRESH_FAILED: 502,
    AI_PROVIDER_ERROR: 502,
    AI_MODEL_FETCH_FAILED: 502,
    AI_MODEL_NOT_FOUND: 404,
    AI_SESSION_NOT_FOUND: 404,
    AI_MESSAGE_NOT_FOUND: 404,
    AI_PROMPT_NOT_FOUND: 404,
    AI_ATTACHMENT_NOT_FOUND: 404,
    AI_ATTACHMENT_TOO_LARGE: 413,
    AI_ATTACHMENT_INVALID_TYPE: 422,
    AI_COMPLETION_FAILED: 502,
}

export const getStatusCode = (code: ErrorCode) => STATUS_MAP[code] ?? 500

export const createAppError = (code: ErrorCode, details?: Record<string, unknown>): AppError => ({
    code,
    message: ERROR_MESSAGE[code],
    statusCode: getStatusCode(code),
    details,
})

export const isAppError = (error: unknown): error is AppError =>
    typeof error === 'object' && error !== null && 'code' in error && 'message' in error && 'statusCode' in error
